### PR TITLE
Contacts view

### PR DESCRIPTION
**Pull request by LIL717**
prayer journal scope changes and bug fixes for:
constraints on Announcement label in Progress View
fix color on Progress View
add first name as a sort descriptor on People table

### CODE REVIEW

**Comment by LIL717** [comment]
Good insight for search on Notes,   reworked that method to combine and present all the results together sorted by lastUpdatedDate -  will want to do more testing when I have a lot of notes, but it is working with my small set of note.
As a part of that, added some logic to deal with the first name-space-last name in the search  - now the logic looks for a space in the search text and assumes that to be a split between a first and last name - which works for the majority of English names, not sure how this works with Chinese and it doesn't work at all for people like Jessica Jo de Reuter whose first name and last name both have spaces.  But its covering most cases now.

**Comment by LIL717** [comment]
Here is the deal with the gray text - there are 2 colors that can be set on the searchController - the background color and the text color.  Unfortunately the cursor in the search field gets the same tint color as the text - so if I set the text to white, you can't see the cursor :(   There may be a way to dig into the views and set the cursor color, but that is a little hacky and might not even be possible.  I think it actually looks ok now that all the scope stuff is taken out.  What do you think?

**Comment by chrislim** [comment]
Cool, yea without the second toggle it seems fine.

**Comment by chrislim** [comment]
I'll merge this change to master.

**Pull request merged**
