### PR TITLE
adjust scrollview for notes text to be above keyboard when editing in No...

### PR DESCRIPTION
**Pull request by LIL717**
...tesViewController

### CODE REVIEW

**Comment by chrislim** [comment]
I'm trying to test it but having some code signing issues--the newest xCode isn't letting me easily fix my code signing issues like before.

**Comment by chrislim** [comment]
Okay i temporarily deleted the test target for now, but won't check it in.
The scrolling works, but when i close the keyboard the field stays small instead of growing back.
Also, the scrollbar is really dark, would be good to make it white.

**Comment by chrislim** [comment]
I saw your most recent comment, if you prefer leaving it black and invisible that's fine.

**Comment by LIL717** [comment]
oh, I forgot that you can manually dismiss the keyboard on the iPad (can't do that on the phone), I fix that 

and I pushed up a fix to the person image in the People table for both iPhone and iPad

**Pull request merged**
